### ISSUE TITLE
updating help

### ISSUE THREAD

**Issue by timothystewart6** [martin26/NewNPCBots#2]
Hi.  Is there any way you can share how to update this to the latest core?

I have tried creating a patch from TrinityCore/3.3.5 330e5b0ebcc6753a355afc3824121c5eba1bf5bc to HEAD then applying it to this however there are some errors.

What's the cleanest way to update this?  Thank you!

**Comment by timothystewart6** [comment]
Even some guidance on merge conflicts would be helpful.  Thanks.

**Comment by timothystewart6** [comment]
Also, I never mentioned that this build is one of the best out there.  I really love the implementation of the bots.  They are nearly perfect for my dungeon crawling needs, at least until the 70s.  I do wish there was a simple way to summon them.  Right now I just copy and paste from my notes.  Not a big deal.   I wish there was an implementation of these bots in 4.3.4/5.x/6.x however I am fine with 3.3.5a.  I am looking for a way to keep the source up to date.  If you plan on keeping this up to date (which it seems so) that's fine too.  I just wanted to have a way to do it myself between releases, and maybe even contribute back to this.  Thanks.

**Comment by victor0x080** [comment]
Hey and sorry im not so much active in to it lately, IRL stuff comes first, The thing is with this kind of manual patch and so on, merging with latest TC commit is coming really hard lately, some things have to be done manually, due to failing build under windows and the manual changes make it fail to build under linux as well, I will however check the soonest I can to update this, but as I saw on AC-WEB TC made lots of changes lately that breaks again the npc bots patch. Yeah I don't think ill up this to 5.x or 6.x, the core is so different that it would require an incredible re-work that im afraid have no interest or time to invest. Also yeah you have to manually spawn them, use macros will save you loads of headaches.

**Comment by timothystewart6** [comment]
No worries.  Thanks for the response!  I will continue to watch this repo and update when you do.  Hoping the 3.3.5 branch gets a new release soon from TrinityCore.  Thanks again.

**Comment by timothystewart6** [comment]
Speaking of, looks like there was one :) https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.62

**Comment by victor0x080** [comment]
Oh TC is always updating you know, its day by day, I tried to use the latest patches from lordpsyan as of september 2016, and they were already broken as well, add to that, I have to manually add changes from thesawolf for the extra features, I really don't know when i'll sit down and have a nice moment with all of that, it will probably take a lot of time for me to consider spend my time with this, its frustrating and I don't have a decent computer to trial and error sadly, will see when I can, but you are more than welcome to try and let me know.

**Comment by timothystewart6** [comment]
Awesome.  I figured I would give it a shot too when they tagged a new release and they did just last week.  I might have some time in the coming weeks.  If I do I will open a PR for you to take a peek at.

**Comment by timothystewart6** [comment]
I'll close this.  Thanks for the help!

**Comment by daodaytop** [comment]
I'll close this. Thanks for the help!

**Comment by victor0x080** [comment]
Well, https://discordapp.com/channels/291115666097045506/325662236549054464

Conan is looking for someone to port npcbots to legion, so you guys are more than welcome to try.
